apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo-java-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: demo-java
    spec:
      containers:
      - name: demo-java
        image: demo-java:v1
        ports:
        - containerPort: 8090
